### ISSUE TITLE
Result of If on line 22 is always false when zsh pipefail is set

### ISSUE THREAD

**Issue by sparcbr** [chrissicool/zsh-256color#4]
https://github.com/chrissicool/zsh-256color/blob/ae40a49ccfc7520d2d7b575aaea160ff876fe3dc/zsh-256color.plugin.zsh#L22

#### grep -q exits after first match, causing a SIGPIPE to be sent to toe which exits (code 141). See below:
```
➤ setopt pipefail
➤ if toe -a | egrep -q "^$TERM256" ; then echo Found; else echo $pipefail; fi
141 0

➤ setopt nopipefail
➤ if toe -a | egrep -q "^$TERM256" ; then echo Found; else echo $pipestatus; fi
Found
```

#### Is there a way to make this work with pipefail set? yes there is:
```
➤ setopt pipefail
```

#### **Fix 1**: don't use -q, and redirect std
```
➤ if toe -a | egrep "^$TERM256" &>/dev/null; then echo Found; else echo $pipestatus; fi
Found
```
#### **Fix 2**: use process substitution
```
➤ if egrep -q "^$TERM256" <(toe -a); then echo Found; else echo $pipestatus; fi
Found
```
#### **Fix 3**: check $pipestatus (ugly)
```
➤ toe -a | egrep -q "^$TERM256"
➤ if [[ $pipestatus[2] -eq 0 ]]; then echo Found; else echo $pipestatus; fi
Found
```

**Comment by chrissicool** [comment]
Thanks for reporting. I will have a look.
